# Generated by Django 5.2.5 on 2025-09-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="api.tag"
            ),
        ),
    ]
