# Generated by Django 5.2.5 on 2025-09-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_recipe_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile_images/default.jpg", upload_to="profile_images/"
            ),
        ),
    ]
