# Generated by Django 5.2.5 on 2025-09-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_profile_bio_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="profile_images/default.jpg",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
