# Generated by Django 5.2.5 on 2025-09-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="prep_time",
            field=models.TextField(),
        ),
    ]
